services:
  apache:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./trastopop:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: trastopopdb
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      LANG: C.UTF-8
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: toor
